#https://app.swaggerhub.com/apis-docs/Guillermo-alt/budget-system/1.0
---
openapi: 3.0.0
info:
  title: social-tecla
  contact:
    name: Guillermo Ortega Vargas
    url: https://github.com/Guillermo-alt
    email: Guillermo76ov@hotmail.com
  version: "1.0"
servers:
- url: http://127.0.0.1:3000
security:
- httpBearer: []
tags:
- name: Misc
paths:
  /budget:
    post:
      tags:
      - Misc
      summary: new Budget
      operationId: newBudget
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/newBudgetRequest'
            example:
              proyect: Vgeneris
              version: 1.0.0
              id_user: "1"
              periods:
              - age: "2021"
                month: Febrero
                income: "2500"
                incomes:
                - value: "5845"
                  id_concept: "2"
                - value: "547"
                  id_concept: "1"
                direct_cost:
                - value: "5789"
                  id_concept: "1"
                - value: "2514"
                  id_concept: "2"
                admin_expenses:
                - value: "547"
                  id_concept: "2"
                - value: "5748"
                  id_concept: "3"
                resources:
                - role: rol 1
                  cost: "125"
                  percentage: "50"
                - role: rol 2
                  cost: "265"
                  percentage: "10"
              - age: "2021"
                month: Marzo
                income: "5784"
                incomes:
                - value: "5898"
                  id_concept: "3"
                - value: "9874"
                  id_concept: "3"
                direct_cost:
                - value: "2564"
                  id_concept: "2"
                - value: "2005"
                  id_concept: "1"
                admin_expenses:
                - value: "5895"
                  id_concept: "1"
                - value: "5895"
                  id_concept: "2"
                resources:
                - role: rol 1
                  cost: "1000"
                  percentage: "50"
                - role: rol 3
                  cost: "1800"
                  percentage: "50"
        required: true
      responses:
        "200":
          description: OK
          headers:
            X-Powered-By:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Express
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            Content-Length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "163"
            ETag:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: W/"a3-81x/lhh36IyywJayrygSjCWE7nw"
            Date:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Fri, 03 Sep 2021 10:30:30 GMT
            Connection:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Keep-Alive:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: timeout=5
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/newBudget'
              example:
                id_budget: 1
                proyect: Tienda online
                version: 1.0.0
                active: true
                id_user: 1
                updatedAt: 2021-09-03T10:30:30.440+0000
                createdAt: 2021-09-03T10:30:30.440+0000
      deprecated: false
  /user/login:
    post:
      tags:
      - Misc
      summary: user login
      operationId: userlogin
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userloginrequest'
            example:
              email: guilwlswe7845@gmail.com
              password: pass
              role: user
        required: true
      responses:
        "200":
          description: OK
          headers:
            X-Powered-By:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Express
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            Content-Length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "207"
            ETag:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: W/"cf-j2yNb5l89/mvt6oWfxT5/39kHwg"
            Date:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Fri, 03 Sep 2021 10:29:14 GMT
            Connection:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Keep-Alive:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: timeout=5
          content:
            application/json; charset=utf-8:
              schema:
                type: string
                example: '"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImVtYWlsIjoiZ3VpbHdsc3dlNzg0NUBnbWFpbC5jb20iLCJwYXNzd29yZCI6InBhc3MiLCJyb2xlIjoidXNlciJ9LCJpYXQiOjE2MzA2NjQ5NTR9.YkivKGcZ_IKfLhZuqI8joALo47mEm057JV80Exs5k60"'
              example: '"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImVtYWlsIjoiZ3VpbHdsc3dlNzg0NUBnbWFpbC5jb20iLCJwYXNzd29yZCI6InBhc3MiLCJyb2xlIjoidXNlciJ9LCJpYXQiOjE2MzA2NjQ5NTR9.YkivKGcZ_IKfLhZuqI8joALo47mEm057JV80Exs5k60"'
      deprecated: false
  /user:
    get:
      tags:
      - Misc
      summary: get user data
      operationId: getuserdata
      parameters: []
      responses:
        "200":
          description: OK
          headers:
            X-Powered-By:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Express
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            Content-Length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "323"
            ETag:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: W/"143-TQp7s0ie1ObFTlIQOWm8DCL5RXs"
            Date:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Fri, 03 Sep 2021 10:31:24 GMT
            Connection:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Keep-Alive:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: timeout=5
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/getuserdata'
              example:
                id_user: 1
                names: Guillermo
                last_names: Ortega Vargas
                email: guilwlswe7845@gmail.com
                userName: Guille
                password: $2b$10$tnpfPLSRsbiLj7WNzRyI7uoHrZd6XbBbjfMveoW6sBF4KH3VSf8Qu
                phone_number: "5515027544"
                active: "1"
                role: user
                createdAt: 2021-09-03T10:28:17.307+0000
                updatedAt: 2021-09-03T10:28:17.307+0000
      deprecated: false
    post:
      tags:
      - Misc
      summary: create user
      operationId: createuser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createuserrequest'
            example:
              names: Guillermo
              last_names: Ortega Vargas
              userName: Guille
              email: guilwlswe7845@gmail.com
              password: pass
              phone_number: "5515027544"
              active: "1"
              role: user
        required: true
      responses:
        "200":
          description: OK
          headers:
            X-Powered-By:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Express
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            Content-Length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "323"
            ETag:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: W/"143-MTtiFb6+I9AyQi8TIoQC3bwwSH0"
            Date:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Fri, 03 Sep 2021 10:28:17 GMT
            Connection:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Keep-Alive:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: timeout=5
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/createuser'
              example:
                id_user: 1
                names: Guillermo
                last_names: Ortega Vargas
                email: guilwlswe7845@gmail.com
                userName: Guille
                password: $2b$10$tnpfPLSRsbiLj7WNzRyI7uoHrZd6XbBbjfMveoW6sBF4KH3VSf8Qu
                phone_number: "5515027544"
                active: "1"
                role: user
                updatedAt: 2021-09-03T10:28:17.307+0000
                createdAt: 2021-09-03T10:28:17.307+0000
      deprecated: false
  /budget/1:
    get:
      tags:
      - Misc
      summary: get budgets user
      operationId: getbudgetsuser
      parameters: []
      responses:
        "200":
          description: OK
          headers:
            X-Powered-By:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Express
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            Content-Length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "165"
            ETag:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: W/"a5-61S7bnUAFBICuu2g1cvFEpi6HoA"
            Date:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Fri, 03 Sep 2021 10:32:02 GMT
            Connection:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Keep-Alive:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: timeout=5
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                example:
                - id_budget: 1
                  proyect: Tienda online
                  version: 1.0.0
                  active: true
                  createdAt: 2021-09-03T10:30:30.440+0000
                  updatedAt: 2021-09-03T10:30:30.440+0000
                  id_user: 1
                items:
                  $ref: '#/components/schemas/getbudgetsuser'
              example:
              - id_budget: 1
                proyect: Tienda online
                version: 1.0.0
                active: true
                createdAt: 2021-09-03T10:30:30.440+0000
                updatedAt: 2021-09-03T10:30:30.440+0000
                id_user: 1
      deprecated: false
  /user/pass:
    put:
      tags:
      - Misc
      summary: change pass user
      operationId: changepassuser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/changepassuserrequest'
            example:
              id_user: "1"
              currentPass: pass1
              newPass: pass
        required: true
      responses:
        "200":
          description: OK
          headers:
            X-Powered-By:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Express
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            Content-Length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "56"
            ETag:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: W/"38-xKLOgDNeweTwq7Duhpb32nEuQPA"
            Date:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Fri, 03 Sep 2021 10:33:25 GMT
            Connection:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Keep-Alive:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: timeout=5
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/changepassuser'
              example:
                id_user: "1"
                response: password changed
                status: 1
      deprecated: false
  /delete:
    put:
      tags:
      - Misc
      summary: delete budget user
      operationId: deletebudgetuser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deletebudgetuserrequest'
            example:
              id_user: "1"
              id_budget: "2"
        required: true
      responses:
        "200":
          description: OK
          headers:
            X-Powered-By:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Express
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            Content-Length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "54"
            ETag:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: W/"36-eGdKaiWQ9aKNwEGocN1nT9LzVgc"
            Date:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Fri, 03 Sep 2021 10:32:40 GMT
            Connection:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Keep-Alive:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: timeout=5
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/deletebudgetuser'
              example:
                id_user: "2"
                response: budget deleted
                status: 1
      deprecated: false
  /concept:
    post:
      tags:
      - Misc
      summary: create concept
      operationId: createconcept
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createconceptrequest'
            example:
              name: Almacenamiento
        required: true
      responses:
        "200":
          description: OK
          headers:
            X-Powered-By:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Express
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            Content-Length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "33"
            ETag:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: W/"21-bwfAsHq/HhZrLCwn8p/eABBBCsQ"
            Date:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Fri, 03 Sep 2021 10:27:46 GMT
            Connection:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Keep-Alive:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: timeout=5
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/createconcept'
              example:
                id_concept: 4
                name: Computo
      deprecated: false
  /concepts:
    get:
      tags:
      - Misc
      summary: get concepts
      operationId: getconcepts
      parameters: []
      responses:
        "200":
          description: OK
          headers:
            X-Powered-By:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Express
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            Content-Length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "158"
            ETag:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: W/"9e-D4U6BH95WyZYGf5vsFp1lO3uFuY"
            Date:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Fri, 03 Sep 2021 10:33:40 GMT
            Connection:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Keep-Alive:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: timeout=5
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                example:
                - id_concept: 1
                  name: Almacenamiento
                - id_concept: 2
                  name: Impresoras y tintas
                - id_concept: 3
                  name: papeleria
                - id_concept: 4
                  name: Computo
                items:
                  $ref: '#/components/schemas/getconcept'
              example:
              - id_concept: 1
                name: Almacenamiento
              - id_concept: 2
                name: Impresoras y tintas
              - id_concept: 3
                name: papeleria
              - id_concept: 4
                name: Computo
      deprecated: false
  /budget/detail/1:
    get:
      tags:
      - Misc
      summary: get Budget Details
      operationId: getBudgetDetails
      parameters: []
      responses:
        "200":
          description: OK
          headers:
            X-Powered-By:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Express
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: '*'
            Content-Length:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: "1451"
            ETag:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: W/"5ab-I++hwfE5JQOffrZvqOAg4JGGZO4"
            Date:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: Fri, 03 Sep 2021 10:31:02 GMT
            Connection:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Keep-Alive:
              style: simple
              explode: false
              content:
                text/plain:
                  schema:
                    type: string
                  example: timeout=5
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                example:
                - id_budget: 1
                  proyect: Tienda online
                  version: 1.0.0
                  active: true
                  createdAt: 2021-09-03T10:30:30.440+0000
                  updatedAt: 2021-09-03T10:30:30.440+0000
                  id_user: 1
                  periods:
                  - id_date: 1
                    month: Febrero
                    age: "2021"
                    income: "2500"
                    id_budget: 1
                    incomes:
                    - id_income: 1
                      value: "5845"
                      id_date: 1
                      id_concept: 2
                    - id_income: 2
                      value: "547"
                      id_date: 1
                      id_concept: 2
                    adminExpenses:
                    - id_expenses: 1
                      value: "547"
                      id_date: 1
                      id_concept: 2
                    - id_expenses: 2
                      value: "5748"
                      id_date: 1
                      id_concept: 2
                    direct_costs:
                    - id_costD: 1
                      value: "5789"
                      id_date: 1
                      id_concept: 2
                    - id_costD: 2
                      value: "2514"
                      id_date: 1
                      id_concept: 2
                    resources:
                    - id_resource: 1
                      role: rol 1
                      cost: "125"
                      percentage: "50"
                      id_date: 1
                    - id_resource: 2
                      role: rol 2
                      cost: "265"
                      percentage: "10"
                      id_date: 1
                  - id_date: 2
                    month: Marzo
                    age: "2021"
                    income: "5784"
                    id_budget: 1
                    incomes:
                    - id_income: 3
                      value: "5898"
                      id_date: 2
                      id_concept: 2
                    - id_income: 4
                      value: "9874"
                      id_date: 2
                      id_concept: 2
                    adminExpenses:
                    - id_expenses: 3
                      value: "5895"
                      id_date: 2
                      id_concept: 2
                    - id_expenses: 4
                      value: "5895"
                      id_date: 2
                      id_concept: 2
                    direct_costs:
                    - id_costD: 3
                      value: "2564"
                      id_date: 2
                      id_concept: 2
                    - id_costD: 4
                      value: "2005"
                      id_date: 2
                      id_concept: 2
                    resources:
                    - id_resource: 3
                      role: rol 1
                      cost: "1000"
                      percentage: "50"
                      id_date: 2
                    - id_resource: 4
                      role: rol 3
                      cost: "1800"
                      percentage: "50"
                      id_date: 2
                items:
                  $ref: '#/components/schemas/getBudgetDetail'
              example:
              - id_budget: 1
                proyect: Tienda online
                version: 1.0.0
                active: true
                createdAt: 2021-09-03T10:30:30.440+0000
                updatedAt: 2021-09-03T10:30:30.440+0000
                id_user: 1
                periods:
                - id_date: 1
                  month: Febrero
                  age: "2021"
                  income: "2500"
                  id_budget: 1
                  incomes:
                  - id_income: 1
                    value: "5845"
                    id_date: 1
                    id_concept: 2
                  - id_income: 2
                    value: "547"
                    id_date: 1
                    id_concept: 2
                  adminExpenses:
                  - id_expenses: 1
                    value: "547"
                    id_date: 1
                    id_concept: 2
                  - id_expenses: 2
                    value: "5748"
                    id_date: 1
                    id_concept: 2
                  direct_costs:
                  - id_costD: 1
                    value: "5789"
                    id_date: 1
                    id_concept: 2
                  - id_costD: 2
                    value: "2514"
                    id_date: 1
                    id_concept: 2
                  resources:
                  - id_resource: 1
                    role: rol 1
                    cost: "125"
                    percentage: "50"
                    id_date: 1
                  - id_resource: 2
                    role: rol 2
                    cost: "265"
                    percentage: "10"
                    id_date: 1
                - id_date: 2
                  month: Marzo
                  age: "2021"
                  income: "5784"
                  id_budget: 1
                  incomes:
                  - id_income: 3
                    value: "5898"
                    id_date: 2
                    id_concept: 2
                  - id_income: 4
                    value: "9874"
                    id_date: 2
                    id_concept: 2
                  adminExpenses:
                  - id_expenses: 3
                    value: "5895"
                    id_date: 2
                    id_concept: 2
                  - id_expenses: 4
                    value: "5895"
                    id_date: 2
                    id_concept: 2
                  direct_costs:
                  - id_costD: 3
                    value: "2564"
                    id_date: 2
                    id_concept: 2
                  - id_costD: 4
                    value: "2005"
                    id_date: 2
                    id_concept: 2
                  resources:
                  - id_resource: 3
                    role: rol 1
                    cost: "1000"
                    percentage: "50"
                    id_date: 2
                  - id_resource: 4
                    role: rol 3
                    cost: "1800"
                    percentage: "50"
                    id_date: 2
      deprecated: false
components:
  schemas:
    newBudgetRequest:
      title: newBudgetRequest
      required:
      - id_user
      - periods
      - proyect
      - version
      type: object
      properties:
        proyect:
          type: string
        version:
          type: string
        id_user:
          type: string
        periods:
          type: array
          items:
            $ref: '#/components/schemas/Period'
      example:
        proyect: Vgeneris
        version: 1.0.0
        id_user: "1"
        periods:
        - age: "2021"
          month: Febrero
          income: "2500"
          incomes:
          - value: "5845"
            id_concept: "2"
          - value: "547"
            id_concept: "1"
          direct_cost:
          - value: "5789"
            id_concept: "1"
          - value: "2514"
            id_concept: "2"
          admin_expenses:
          - value: "547"
            id_concept: "2"
          - value: "5748"
            id_concept: "3"
          resources:
          - role: rol 1
            cost: "125"
            percentage: "50"
          - role: rol 2
            cost: "265"
            percentage: "10"
        - age: "2021"
          month: Marzo
          income: "5784"
          incomes:
          - value: "5898"
            id_concept: "3"
          - value: "9874"
            id_concept: "3"
          direct_cost:
          - value: "2564"
            id_concept: "2"
          - value: "2005"
            id_concept: "1"
          admin_expenses:
          - value: "5895"
            id_concept: "1"
          - value: "5895"
            id_concept: "2"
          resources:
          - role: rol 1
            cost: "1000"
            percentage: "50"
          - role: rol 3
            cost: "1800"
            percentage: "50"
    Period:
      title: Period
      required:
      - admin_expenses
      - age
      - direct_cost
      - income
      - incomes
      - month
      - resources
      type: object
      properties:
        age:
          type: string
        month:
          type: string
        income:
          type: string
        incomes:
          type: array
          items:
            $ref: '#/components/schemas/Income'
        direct_cost:
          type: array
          items:
            $ref: '#/components/schemas/DirectCost'
        admin_expenses:
          type: array
          items:
            $ref: '#/components/schemas/AdminExpense'
        resources:
          type: array
          items:
            $ref: '#/components/schemas/Resource'
      example:
        age: "2021"
        month: Febrero
        income: "2500"
        incomes:
        - value: "5845"
          id_concept: "2"
        - value: "547"
          id_concept: "1"
        direct_cost:
        - value: "5789"
          id_concept: "1"
        - value: "2514"
          id_concept: "2"
        admin_expenses:
        - value: "547"
          id_concept: "2"
        - value: "5748"
          id_concept: "3"
        resources:
        - role: rol 1
          cost: "125"
          percentage: "50"
        - role: rol 2
          cost: "265"
          percentage: "10"
    Income:
      title: Income
      required:
      - id_concept
      - value
      type: object
      properties:
        value:
          type: string
        id_concept:
          type: string
      example:
        value: "5845"
        id_concept: "2"
    DirectCost:
      title: DirectCost
      required:
      - id_concept
      - value
      type: object
      properties:
        value:
          type: string
        id_concept:
          type: string
      example:
        value: "5789"
        id_concept: "1"
    AdminExpense:
      title: AdminExpense
      required:
      - id_concept
      - value
      type: object
      properties:
        value:
          type: string
        id_concept:
          type: string
      example:
        value: "547"
        id_concept: "2"
    Resource:
      title: Resource
      required:
      - cost
      - percentage
      - role
      type: object
      properties:
        role:
          type: string
        cost:
          type: string
        percentage:
          type: string
      example:
        role: rol 1
        cost: "125"
        percentage: "50"
    newBudget:
      title: newBudget
      required:
      - active
      - createdAt
      - id_budget
      - id_user
      - proyect
      - updatedAt
      - version
      type: object
      properties:
        id_budget:
          type: integer
          format: int32
        proyect:
          type: string
        version:
          type: string
        active:
          type: boolean
        id_user:
          type: integer
          format: int32
        updatedAt:
          type: string
        createdAt:
          type: string
      example:
        id_budget: 1
        proyect: Tienda online
        version: 1.0.0
        active: true
        id_user: 1
        updatedAt: 2021-09-03T10:30:30.440+0000
        createdAt: 2021-09-03T10:30:30.440+0000
    userloginrequest:
      title: userloginrequest
      required:
      - email
      - password
      - role
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        role:
          type: string
      example:
        email: guilwlswe7845@gmail.com
        password: pass
        role: user
    getuserdata:
      title: getuserdata
      required:
      - active
      - createdAt
      - email
      - id_user
      - last_names
      - names
      - password
      - phone_number
      - role
      - updatedAt
      - userName
      type: object
      properties:
        id_user:
          type: integer
          format: int32
        names:
          type: string
        last_names:
          type: string
        email:
          type: string
        userName:
          type: string
        password:
          type: string
        phone_number:
          type: string
        active:
          type: string
        role:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      example:
        id_user: 1
        names: Guillermo
        last_names: Ortega Vargas
        email: guilwlswe7845@gmail.com
        userName: Guille
        password: $2b$10$tnpfPLSRsbiLj7WNzRyI7uoHrZd6XbBbjfMveoW6sBF4KH3VSf8Qu
        phone_number: "5515027544"
        active: "1"
        role: user
        createdAt: 2021-09-03T10:28:17.307+0000
        updatedAt: 2021-09-03T10:28:17.307+0000
    getbudgetsuser:
      title: getbudgetsuser
      required:
      - active
      - createdAt
      - id_budget
      - id_user
      - proyect
      - updatedAt
      - version
      type: object
      properties:
        id_budget:
          type: integer
          format: int32
        proyect:
          type: string
        version:
          type: string
        active:
          type: boolean
        createdAt:
          type: string
        updatedAt:
          type: string
        id_user:
          type: integer
          format: int32
      example:
        id_budget: 1
        proyect: Tienda online
        version: 1.0.0
        active: true
        createdAt: 2021-09-03T10:30:30.440+0000
        updatedAt: 2021-09-03T10:30:30.440+0000
        id_user: 1
    changepassuserrequest:
      title: changepassuserrequest
      required:
      - currentPass
      - id_user
      - newPass
      type: object
      properties:
        id_user:
          type: string
        currentPass:
          type: string
        newPass:
          type: string
      example:
        id_user: "1"
        currentPass: pass1
        newPass: pass
    changepassuser:
      title: changepassuser
      required:
      - id_user
      - response
      - status
      type: object
      properties:
        id_user:
          type: string
        response:
          type: string
        status:
          type: integer
          format: int32
      example:
        id_user: "1"
        response: password changed
        status: 1
    deletebudgetuserrequest:
      title: deletebudgetuserrequest
      required:
      - id_budget
      - id_user
      type: object
      properties:
        id_user:
          type: string
        id_budget:
          type: string
      example:
        id_user: "1"
        id_budget: "2"
    deletebudgetuser:
      title: deletebudgetuser
      required:
      - id_user
      - response
      - status
      type: object
      properties:
        id_user:
          type: string
        response:
          type: string
        status:
          type: integer
          format: int32
      example:
        id_user: "2"
        response: budget deleted
        status: 1
    createconceptrequest:
      title: createconceptrequest
      required:
      - name
      type: object
      properties:
        name:
          type: string
      example:
        name: Almacenamiento
    createconcept:
      title: createconcept
      required:
      - id_concept
      - name
      type: object
      properties:
        id_concept:
          type: integer
          format: int32
        name:
          type: string
      example:
        id_concept: 4
        name: Computo
    getconcept:
      title: getconcept
      required:
      - id_concept
      - name
      type: object
      properties:
        id_concept:
          type: integer
          format: int32
        name:
          type: string
      example:
        id_concept: 1
        name: Almacenamiento
    createuserrequest:
      title: createuserrequest
      required:
      - active
      - email
      - last_names
      - names
      - password
      - phone_number
      - role
      - userName
      type: object
      properties:
        names:
          type: string
        last_names:
          type: string
        userName:
          type: string
        email:
          type: string
        password:
          type: string
        phone_number:
          type: string
        active:
          type: string
        role:
          type: string
      example:
        names: Guillermo
        last_names: Ortega Vargas
        userName: Guille
        email: guilwlswe7845@gmail.com
        password: pass
        phone_number: "5515027544"
        active: "1"
        role: user
    createuser:
      title: createuser
      required:
      - active
      - createdAt
      - email
      - id_user
      - last_names
      - names
      - password
      - phone_number
      - role
      - updatedAt
      - userName
      type: object
      properties:
        id_user:
          type: integer
          format: int32
        names:
          type: string
        last_names:
          type: string
        email:
          type: string
        userName:
          type: string
        password:
          type: string
        phone_number:
          type: string
        active:
          type: string
        role:
          type: string
        updatedAt:
          type: string
        createdAt:
          type: string
      example:
        id_user: 1
        names: Guillermo
        last_names: Ortega Vargas
        email: guilwlswe7845@gmail.com
        userName: Guille
        password: $2b$10$tnpfPLSRsbiLj7WNzRyI7uoHrZd6XbBbjfMveoW6sBF4KH3VSf8Qu
        phone_number: "5515027544"
        active: "1"
        role: user
        updatedAt: 2021-09-03T10:28:17.307+0000
        createdAt: 2021-09-03T10:28:17.307+0000
    getBudgetDetail:
      title: getBudgetDetail
      required:
      - active
      - createdAt
      - id_budget
      - id_user
      - periods
      - proyect
      - updatedAt
      - version
      type: object
      properties:
        id_budget:
          type: integer
          format: int32
        proyect:
          type: string
        version:
          type: string
        active:
          type: boolean
        createdAt:
          type: string
        updatedAt:
          type: string
        id_user:
          type: integer
          format: int32
        periods:
          type: array
          items:
            $ref: '#/components/schemas/Period1'
      example:
        id_budget: 1
        proyect: Tienda online
        version: 1.0.0
        active: true
        createdAt: 2021-09-03T10:30:30.440+0000
        updatedAt: 2021-09-03T10:30:30.440+0000
        id_user: 1
        periods:
        - id_date: 1
          month: Febrero
          age: "2021"
          income: "2500"
          id_budget: 1
          incomes:
          - id_income: 1
            value: "5845"
            id_date: 1
            id_concept: 2
          - id_income: 2
            value: "547"
            id_date: 1
            id_concept: 2
          adminExpenses:
          - id_expenses: 1
            value: "547"
            id_date: 1
            id_concept: 2
          - id_expenses: 2
            value: "5748"
            id_date: 1
            id_concept: 2
          direct_costs:
          - id_costD: 1
            value: "5789"
            id_date: 1
            id_concept: 2
          - id_costD: 2
            value: "2514"
            id_date: 1
            id_concept: 2
          resources:
          - id_resource: 1
            role: rol 1
            cost: "125"
            percentage: "50"
            id_date: 1
          - id_resource: 2
            role: rol 2
            cost: "265"
            percentage: "10"
            id_date: 1
        - id_date: 2
          month: Marzo
          age: "2021"
          income: "5784"
          id_budget: 1
          incomes:
          - id_income: 3
            value: "5898"
            id_date: 2
            id_concept: 2
          - id_income: 4
            value: "9874"
            id_date: 2
            id_concept: 2
          adminExpenses:
          - id_expenses: 3
            value: "5895"
            id_date: 2
            id_concept: 2
          - id_expenses: 4
            value: "5895"
            id_date: 2
            id_concept: 2
          direct_costs:
          - id_costD: 3
            value: "2564"
            id_date: 2
            id_concept: 2
          - id_costD: 4
            value: "2005"
            id_date: 2
            id_concept: 2
          resources:
          - id_resource: 3
            role: rol 1
            cost: "1000"
            percentage: "50"
            id_date: 2
          - id_resource: 4
            role: rol 3
            cost: "1800"
            percentage: "50"
            id_date: 2
    Period1:
      title: Period1
      required:
      - adminExpenses
      - age
      - direct_costs
      - id_budget
      - id_date
      - income
      - incomes
      - month
      - resources
      type: object
      properties:
        id_date:
          type: integer
          format: int32
        month:
          type: string
        age:
          type: string
        income:
          type: string
        id_budget:
          type: integer
          format: int32
        incomes:
          type: array
          items:
            $ref: '#/components/schemas/Income1'
        adminExpenses:
          type: array
          items:
            $ref: '#/components/schemas/AdminExpense1'
        direct_costs:
          type: array
          items:
            $ref: '#/components/schemas/DirectCost1'
        resources:
          type: array
          items:
            $ref: '#/components/schemas/Resource1'
      example:
        id_date: 1
        month: Febrero
        age: "2021"
        income: "2500"
        id_budget: 1
        incomes:
        - id_income: 1
          value: "5845"
          id_date: 1
          id_concept: 2
        - id_income: 2
          value: "547"
          id_date: 1
          id_concept: 2
        adminExpenses:
        - id_expenses: 1
          value: "547"
          id_date: 1
          id_concept: 2
        - id_expenses: 2
          value: "5748"
          id_date: 1
          id_concept: 2
        direct_costs:
        - id_costD: 1
          value: "5789"
          id_date: 1
          id_concept: 2
        - id_costD: 2
          value: "2514"
          id_date: 1
          id_concept: 2
        resources:
        - id_resource: 1
          role: rol 1
          cost: "125"
          percentage: "50"
          id_date: 1
        - id_resource: 2
          role: rol 2
          cost: "265"
          percentage: "10"
          id_date: 1
    Income1:
      title: Income1
      required:
      - id_concept
      - id_date
      - id_income
      - value
      type: object
      properties:
        id_income:
          type: integer
          format: int32
        value:
          type: string
        id_date:
          type: integer
          format: int32
        id_concept:
          type: integer
          format: int32
      example:
        id_income: 1
        value: "5845"
        id_date: 1
        id_concept: 2
    AdminExpense1:
      title: AdminExpense1
      required:
      - id_concept
      - id_date
      - id_expenses
      - value
      type: object
      properties:
        id_expenses:
          type: integer
          format: int32
        value:
          type: string
        id_date:
          type: integer
          format: int32
        id_concept:
          type: integer
          format: int32
      example:
        id_expenses: 1
        value: "547"
        id_date: 1
        id_concept: 2
    DirectCost1:
      title: DirectCost1
      required:
      - id_concept
      - id_costD
      - id_date
      - value
      type: object
      properties:
        id_costD:
          type: integer
          format: int32
        value:
          type: string
        id_date:
          type: integer
          format: int32
        id_concept:
          type: integer
          format: int32
      example:
        id_costD: 1
        value: "5789"
        id_date: 1
        id_concept: 2
    Resource1:
      title: Resource1
      required:
      - cost
      - id_date
      - id_resource
      - percentage
      - role
      type: object
      properties:
        id_resource:
          type: integer
          format: int32
        role:
          type: string
        cost:
          type: string
        percentage:
          type: string
        id_date:
          type: integer
          format: int32
      example:
        id_resource: 1
        role: rol 1
        cost: "125"
        percentage: "50"
        id_date: 1
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
